export enum ParcelStatus {
  ID_ADDED = 'ID_ADDED',
  IN_TRANSIT = 'IN_TRANSIT',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  MISSING_IN_ACTION = 'MISSING_IN_ACTION',
  CANCELLED = 'CANCELLED'
}
